version: "3.7"

services:
  keycloak:
    restart: always
    container_name: keycloak
    image: jboss/keycloak:6.0.1
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/samplerealm.json
    command:
      - "-b 0.0.0.0"
    volumes:
      - "./samplerealm.json:/opt/jboss/keycloak/samplerealm.json"
